#!/usr/bin/python

import json
import sys
from datetime import datetime
from socket import socket, AF_INET, SOCK_DGRAM
from struct import Struct

# for logging to stdout
def log_normal(string):
    # redirect print output to stdout
    # this should be sys.stdout but dunno why its not working. fk it for now
    print >> sys.stderr, (datetime.now().strftime("%H:%M:%S.%f") + " " + string + "\n")

# for logging to stderr
def log_error(string):
    # redirect print output to stderr
    print >> sys.stderr, (datetime.now().strftime("%H:%M:%S.%f") + " " + string + "\n")

sequence_num = 0
window_size = 100
packet_data = None
sequence_packet_map = {}
acks_sent = []
packet_struct = Struct('I 1400s ? I')

ip_port = sys.argv[1]
udp_ip = ip_port[0:ip_port.find(":")]
udp_port = int(ip_port[ip_port.find(":")+1:])
dest = (udp_ip, udp_port)

# connect to socket and setup attributes
def setup_socket():
    my_socket = socket(AF_INET, SOCK_DGRAM)
    my_socket.settimeout(1.2)
    return my_socket

# Set up the socket
sock = setup_socket()

# Retrieve data from STDIN
def read_stdin():
    final_data = ""
    while True:
        intake = sys.stdin.read(1400)
        if len(intake) > 1:
            final_data += intake
        else:
            return final_data

def send_packet():
    for w in range(window_size):
        data = packet_data[:1400]

        if len(data) > 0:
            global sequence_num
            global packet_data
            packet_data = packet_data[1400:]
            packet = packet_struct.pack(sequence_num, data, False, window_size)
            assert (len(packet) <= 1472), "ERROR: Datagram is longer than 1472 bytes!!!"

            sequence_num += len(data)
            if sock.sendto(packet, dest) < len(packet):
                log_error("[error] unable to fully send packet")
            else:
                global sequence_packet_map
                tupl = (packet, len(data))
                sequence_packet_map[sequence_num] = tupl
                log_normal("[send data] " + str(sequence_num) + " (" + str(len(data)) + ")")
        else:
            if w == 0:
                return False
    return True

def resend_packet(sequence):
    global sequence_packet_map
    (data, size) = sequence_packet_map[sequence]
    if sock.sendto(data, dest) < len(data):
        log_error("[error] unable to fully send packet")
    else:
        log_normal("[send data] {} ({})".format(str(sequence), str(size)))

# initialize the permanent loop that reads from STDIN
packet_data = read_stdin()

# first, send the first packet
send_packet()

# main loop where the 'sending logic' happens
while True:
    target_acks = []

    # iterate through window to get packet and target acks
    for w in range(window_size):
        flag = (sequence_num not in target_acks) and (sequence_num not in acks_sent)
        if flag:
            target_acks.append(sequence_num)
        packet = sequence_packet_map.get(sequence_num, None)
        prev_packet = sequence_packet_map.get(sequence_num - packet[1], None)
        if not prev_packet:
            break
        sequence_num = sequence_num - packet[1]

    while True:
        if len(target_acks) == 0:
            break

        result = None
        try:
            result = sock.recvfrom(1500)
        except:
            for sequence_num in target_acks:
                resend_packet(sequence_num)
            continue

        if result:
            (data, addr) = result
            try:
                decoded = json.loads(data)
                ack = decoded['ack']

                # add the acknowledgement to relevant lists to keep track
                if ack in target_acks:
                    acks_sent.append(ack)
                    target_acks.remove(ack)
                    log_normal("[recv ack] " + str(ack))

            except (ValueError, KeyError, TypeError):
                log_error("[recv corrupt packet]")
        else:
            log_error("[error] timeout")
            sys.exit(-1)

    # shift window to right
    window_size += 1

    # send packet, break if done
    success_or_nah = send_packet()
    if not success_or_nah:
        break

# send 'last termination packets' before ending gracefully
for w in range(7):
    last_packet = packet_struct.pack(sequence_num, "", True, window_size)
    sock.sendto(last_packet, dest)

log_normal("[completed]")
sys.exit(0)
